// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BBS.Domain
{
    public partial class Account
    {
        public int Id { get; set; }
        public string Account1 { get; set; }
        public string Password { get; set; }
        public string NickName { get; set; }
        public string Avatar { get; set; }
        public int Integral { get; set; }
        public DateTime CreateTime { get; set; }
    }
}