// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BBS.Domain
{
    public partial class Comment
    {
        public int Id { get; set; }
        public int TopicId { get; set; }
        public int AccountId { get; set; }
        public int QuoteAccountId { get; set; }
        public string Contents { get; set; }
        public int ThumbsUpCount { get; set; }
        public int ThumbsDownCount { get; set; }
        public DateTime CreateTime { get; set; }
    }
}