// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BBS.Domain
{
    public partial class Feedback
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Contact { get; set; }
        public string Contents { get; set; }
        public DateTime CreateTime { get; set; }
    }
}