// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BBS.Domain
{
    public partial class Topic
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int AccountId { get; set; }
        public int CatalogId { get; set; }
        public string Contents { get; set; }
        public int ThumbsUpCount { get; set; }
        public int ThumbsDownCount { get; set; }
        public int TrailCount { get; set; }
        public DateTime CreateTime { get; set; }
        public DateTime LastUpdateTime { get; set; }
    }
}