// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BBS.Domain
{
    public partial class Trail
    {
        public int Id { get; set; }
        public int AccountId { get; set; }
        public int ItemId { get; set; }
        public DateTime CreateTime { get; set; }
    }
}